config/routes.rb
Athens::Application.routes.draw do
  resources :specialties

  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'static_pages#home'

  match '/signin'                   => 'sessions#new',      :as => :signin
  match "/auth/:provider/callback"  => "sessions#create"
  match '/auth/failure'             => 'sessions#failure'

  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/watermark', to: 'static_pages#watermark'
  match '/contact',   to: 'static_pages#contact'
  match '/join',      to: 'static_pages#join'
  match '/faq',       to: 'static_pages#faq'
  match '/terms',     to: 'static_pages#terms'
  match '/tweets',    to: 'static_pages#tweets'
  
  resources :skills
  resources :occupations
  resources :profiles
  resources :identities

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
	belongs_to :user
	has_many :specialties
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :occupations
	
  	mount_uploader :photo, PhotoUploader

  	before_save :set_status

  	def set_status
  		self.status = "inactive" if self.status.nil?
  	end


end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :user
	belongs_to :occupation
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	devise 	:database_authenticatable, :registerable, :recoverable, :rememberable, 
			:trackable, :authentication_keys => [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  # GET /occupations
  # GET /occupations.json
  def index
    @occupations = Occupation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @occupations }
    end
  end

  # GET /occupations/1
  # GET /occupations/1.json
  def show
    @occupation = Occupation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @occupation }
    end
  end

  # GET /occupations/new
  # GET /occupations/new.json
  def new
    @occupation = Occupation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @occupation }
    end
  end

  # GET /occupations/1/edit
  def edit
    @occupation = Occupation.find(params[:id])
  end

  # POST /occupations
  # POST /occupations.json
  def create
    @occupation = Occupation.new(params[:occupation])

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to @occupation, notice: 'Occupation was successfully created.' }
        format.json { render json: @occupation, status: :created, location: @occupation }
      else
        format.html { render action: "new" }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /occupations/1
  # PUT /occupations/1.json
  def update
    @occupation = Occupation.find(params[:id])

    respond_to do |format|
      if @occupation.update_attributes(params[:occupation])
        format.html { redirect_to @occupation, notice: 'Occupation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1
  # DELETE /occupations/1.json
  def destroy
    @occupation = Occupation.find(params[:id])
    @occupation.destroy

    respond_to do |format|
      format.html { redirect_to occupations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json

  before_filter :authenticate_user!, :except => [:index]
   # :only => 

  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# def create
	#   auth = request.env["omniauth.auth"]
	#   user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	#   session[:user_id] = user.id
	#   redirect_to root_url, :notice => "Signed in!"
	# end

	# def destroy
	#   session[:user_id] = nil
	#   redirect_to root_url, :notice => "Signed out!"
	# end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < InheritedResources::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def join
  end
  
  def watermark
  end

  def faq
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact/contact.html.erb
<div class="note">Drop us a note</div>


<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/contact/new.html.erb
<!-- Written By Seth Howard -->

<div class="contact-page">
  <div class="subheader">
    <div class="content">
      <div class="title">Join Us!</div>
      <div class="sub-title">Become a part of the local tech scene and help us showcase what Utah has to offer.</div>
    </div>
  </div>
  <div class="contact-content">
    <div class="left-bar">
		<div class ="join-text">
			Doing big things in the 801? Include links to relevant sites, apps, or profiles that showcase your work, open-source contributions, and community involvement. <p>We'll contact you soon for a brief Q&A or hangout. 
		</div>
      <div class="utah-skyline"></div>
	  <!-- <div class="floating-text">
        <div class="questions">questions ?</div>
        <div class="comments">comments</div>
        <div class="ideas">ideas</div>
        <div class="jokes">jokes</div>
        <div class="tell-us">tell us about it.</div>
      </div> -->
    </div>
    <div class="right-bar">
      <%= form_for @message, :url => contact_path do |form| %>
        <table>
          <tr>
            <td><%= form.label :name %></td>
            <td><%= form.text_field :name %></td>
          </tr>
          <tr>
            <td><%= form.label :email %></td>
            <td><%= form.text_field :email %></td>
          </tr>
          <tr>
            <td><%= form.label :subject %></td>
            <td><%= form.text_field :subject %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= form.text_area :body %></td>
          </tr>
          <tr>
            <td></td>
            <td class="center contact-submit"><%= form.submit "Send", :class => 'button' %><div class="loader"></div></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
  <script src="/assets/contact.js" type="text/javascript"></script>
</div>

app/views/occupations/_form.html.erb
<%= form_for(@occupation) do |f| %>
  <% if @occupation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@occupation.errors.count, "error") %> prohibited this occupation from being saved:</h2>

      <ul>
      <% @occupation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/occupations/edit.html.erb
<h1>Editing occupation</h1>

<%= render 'form' %>

<%= link_to 'Show', @occupation %> |
<%= link_to 'Back', occupations_path %>

app/views/occupations/index.html.erb
<h1>Listing occupations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @occupations.each do |occupation| %>
  <tr>
    <td><%= occupation.name %></td>
    <td><%= link_to 'Show', occupation %></td>
    <td><%= link_to 'Edit', edit_occupation_path(occupation) %></td>
    <td><%= link_to 'Destroy', occupation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Occupation', new_occupation_path %>

app/views/occupations/new.html.erb
<h1>New occupation</h1>

<%= render 'form' %>

<%= link_to 'Back', occupations_path %>

app/views/occupations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @occupation.name %>
</p>


<%= link_to 'Edit', edit_occupation_path(@occupation) %> |
<%= link_to 'Back', occupations_path %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="photo">
	  <%= f.label :photo %><br />
	  <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :employer %><br />
    <%= f.text_field :employer %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Headline</th>
    <th>Title</th>
    <th>Employer</th>
    <th>Bio</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.headline %></td>
    <td><%= profile.title %></td>
    <td><%= profile.employer %></td>
    <td><%= profile.bio %></td>
    <td><%= profile.birthday %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @profile.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @profile.last_name %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag(@profile.photo_url, :width => 600) if @profile.photo.present? %>
  
</p>

<p>
  <b>Headline:</b>
  <%= @profile.headline %>
</p>

<p>
  <b>Title:</b>
  <%= @profile.title %>
</p>

<p>
  <b>Employer:</b>
  <%= @profile.employer %>
</p>

<p>
  <b>Bio</b>
  <%= @profile.bio %>
</p>
<p>
  <b>Birthday:</b>
  <%= @profile.birthday %>
</p>

<p>
  <b>User:</b>
  <%= @profile.user_id %>
</p>

<p>
  <b>Contact Email:</b>
  <%= @profile.contact_email %>
</p>

<p>
  <b>Private Message:</b>
  <%= @profile.message %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/specialties/_form.html.erb
<%= form_for(@specialty) do |f| %>
  <% if @specialty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialty.errors.count, "error") %> prohibited this specialty from being saved:</h2>

      <ul>
      <% @specialty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialties/edit.html.erb
<h1>Editing specialty</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialty %> |
<%= link_to 'Back', specialties_path %>

app/views/specialties/index.html.erb
<h1>Listing specialties</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specialties.each do |specialty| %>
  <tr>
    <td><%= specialty.name %></td>
    <td><%= link_to 'Show', specialty %></td>
    <td><%= link_to 'Edit', edit_specialty_path(specialty) %></td>
    <td><%= link_to 'Destroy', specialty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Specialty', new_specialty_path %>

app/views/specialties/new.html.erb
<h1>New specialty</h1>

<%= render 'form' %>

<%= link_to 'Back', specialties_path %>

app/views/specialties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @specialty.name %>
</p>


<%= link_to 'Edit', edit_specialty_path(@specialty) %> |
<%= link_to 'Back', specialties_path %>

app/views/static_pages/about.html.erb
<div class="center hero-unit">
  <h2><span style="font-size:14px; font-weight:bold">About</br></span>We Are Utah Tech</h2>
  <body>
  	<p>Big things are happening in Utah. Inspired by the thriving tech community in New York (link), We Are Utah Tech features the people who are making it happen here in Utah. </p>

  	<p>Our goal is to embrace the local tech scene and showcase all it has to offer. From designer to coder to entrepreneur, we know you are doing amazing things and others want to know about them. We'll feature new projects, people and designs frequently.
	</p>

    <p>General expectations for We Are Utah Tech peeps:
		<ul class="a">
			<li>some published work or portfolio available online</li>
			<li>you are local!</li>
			<li>willing to upload a bio and pic</li>
			<li>you are active in the tech community</li>
			<li>you love lamp</li>
		</ul>
	</p>
	
	<p>We hope you'll take a few minutes to browse the site, check out new projects, and a possibly meet your next tech partner. This site was made by @sethhoward, @jeffpotter, and @kyleclegg.</p>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
  
	</body>
</div>

app/views/static_pages/contact.html.erb
<div class="center hero-unit">
  <h1>Drop us a line...</h1>

  <h2>We would love to hear from you!</h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/faq.html.erb
<div class="center hero-unit">
  <h1>What is this glorious site?</h1>

  <h2>We would love to hear from you!</h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/home.html.erb
<script src="/assets/app/data.js"></script>
<script src="/assets/app/vendors/require.js" data-main="assets/app/main"></script>

<% if user_signed_in? %>
	<p>Hello <%= current_user.email %></p>
	<%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
<% else %>
	
<% end %>

<script type="text/javascript">
	//old stuff
	//<%= link_to "Sign Up", new_user_registration_path %>
	//<%= link_to "Log In", new_user_session_path %>
	window.user = <%= current_user.to_json.html_safe %>;
	console.log('<%= destroy_user_session_path %>');
	console.log('<%= new_user_registration_path %>');
	console.log('<%= new_user_session_path %>');
</script>

app/views/static_pages/join.html.erb
<div>
	<div class="wrap">
		<div class=left_col>
			<h1>Join We Are Utah Tech</h1>
			<div class="text">
				<p>Become a part of the local tech scene and help us showcase what Utah has to offer.</p>
				<p>Doing big things in the 801? Include links to relevant sites, apps, or profiles that showcase your work, open-source contributions, and community involvement. We'll contact you soon for a brief Q&A or hangout.</p>
			    <p>General expectations for We Are Utah Tech peeps:
					<ul class="a">
						<li>some published work or portfolio available online</li>
						<li>you are local!</li>
						<li>willing to upload a bio and pic</li>
						<li>you are active in the tech community</li>
						<li>you love lamp</li>
					</ul>
				</p>
				<form action="javascript:void(0);">
		  			<fieldset>
		  				<legend>Contact Info (private)</legend>
		  					Contact Email: <input type="text"><br>
					  		Best method of contact: 
					  		<select>
					  			<option>Google Hangout</option>
					  			<option>Skype</option>
					  			<option>Phone</option>
					  			<option>Lunch</option>
					  		</select>

			  				Message:
							<textarea style="width:300px;"></textarea>
		  			</fieldset>
		  		</form>
			</div>
		</div>
		<div class="right_col">
			<form action="javascript:void(0);">
	  			<fieldset>
	  				<legend>Profile Info (public)</legend>
	  					First Name: <input type="text"><br>
				  		Last Name: <input type="text"><br>
				  		Date of Birth: <input type="text"><br>
						Tagline: <input type="text"><br>
						Employer: <input type="text"><br>
						Website: <input type="text"><br>
						Twitter: <input type="text"><br>
	  				<legend>Occupation</legend>
	  					<div id="occupations">
		  					<button class="btn" id="dev">Developer</button>
		  					<button class="btn" id="design">Designer</button>
		  					<button class="btn" id="founder">Founder</button>
		  					<!--
		  					<button class="btn btn-info">Investors</button>
		  					<button class="btn btn-info">Executive</button>
		  					<button class="btn btn-info">Business People</button>
		  					<button class="btn btn-info">Educators</button>
		  					-->
	  					</div>
	  				<legend>Specialty</legend>
	  					<div id="developer-skills">
	  						<h5>Developer Skills</h5>
		  					<button class="btn btn-info">Ruby</button>
		  					<button class="btn btn-info">JavaScript</button>
		  					<button class="btn btn-info">Java</button>
		  					<button class="btn btn-info">Objective-C</button>
		  					<button class="btn btn-info">PHP</button>
		  					<button class="btn btn-info">C++</button>
		  					<!-- <button class="btn btn-info">C#</button> -->
		  					<button class="btn btn-info">Android</button>
	  					</div>
	  					<div id="designer-skills">
	  						<h5>Designer Skills</h5>
	  						<button class="btn btn-info">Web Design</button>
		  					<button class="btn btn-info">Illustration</button>
		  					<button class="btn btn-info">jQuery</button>
		  					<button class="btn btn-info">Typography</button>
		  					<button class="btn btn-info">Logo Design</button>
		  					<button class="btn btn-info">UX</button>
		  					<button class="btn btn-info">UI Design</button>
		  					<button class="btn btn-info">Branding</button>
		  					<button class="btn btn-info">Animation</button>
		  					<button class="btn btn-info">Photoshop</button>
		  					<button class="btn btn-info">Illustrator</button>
		  					<button class="btn btn-info">CSS</button>
		  					<button class="btn btn-info">Flash</button>
		  				</div>
		  				<div id="founder-skills">
		  					<h5>Founder Skills</h5>
		  					<button class="btn btn-info">Business Dev</button>
		  					<button class="btn btn-info">Tech Lead</button>
		  					<button class="btn btn-info">CEO's</button>
		  					<button class="btn btn-info">Lawyers</button>
		  					<button class="btn btn-info">Director</button>
		  				</div>
		  			<legend>Bio</legend>
		  				<textarea style="width:300px;"></textarea>
						
					Other links: <input type="text"><br>
		  				<button class="btn-large btn-success">Submit</button>
	  			</fieldset>
	  		</form>
		</div>
	</div>
</div>
<script>
	$(function(){
		$('#developer-skills').hide();
		$('#founder-skills').hide();
		$('#designer-skills').hide();

		$('#occupations button').on('click',function(){
			var val = $(this).attr('id');
			console.log(val);
			if(val === 'dev'){
				$('#developer-skills').show();
				$('#designer-skills').hide();
				$('#founder-skills').hide();
			}	
			if(val === 'design'){
				$('#developer-skills').hide();
				$('#designer-skills').show();
				$('#founder-skills').hide();
			}	
			if(val === 'founder'){
				$('#developer-skills').hide();
				$('#designer-skills').hide();
				$('#founder-skills').show();
			}	
		});

		$('button').on('click',function(){
			console.log($(this).text());
			$(this).removeClass("btn-info");
			$(this).addClass("btn-primary");
		});

	});
	
</script>

app/views/static_pages/terms.html.erb
<div class="center hero-unit">
  <h1>What is this glorious site?</h1>

  <h2>We would love to hear from you!</h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/tweets.html.erb
<div class="center hero-unit">
	<a class="twitter-timeline" href="https://twitter.com/weareutahtech" data-widget-id="316033581644386304">Tweets by @weareutahtech</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  
</div>