config/routes.rb
Athens::Application.routes.draw do
  resources :specialties

  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'static_pages#home'

  match '/signin'                   => 'sessions#new',      :as => :signin
  match "/auth/:provider/callback"  => "sessions#create"
  match '/auth/failure'             => 'sessions#failure'

  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/watermark', to: 'static_pages#watermark'
  match '/contact',   to: 'static_pages#contact'
  match '/join',      to: 'static_pages#join'
  match '/faq',       to: 'static_pages#faq'
  match '/terms',     to: 'static_pages#terms'
  match '/tweets',    to: 'static_pages#tweets'
  
  resources :skills
  resources :occupations
  resources :profiles
  resources :identities

  match ':controller(/:action(/:id))(.:format)'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/occupation.rb
class Occupation < ActiveRecord::Base
	belongs_to :user
	has_many :specialties
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :occupations
	
  	mount_uploader :photo, PhotoUploader

  	before_save :set_status

  	def set_status
  		self.status = "inactive" if self.status.nil?
  	end


end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	belongs_to :user
	belongs_to :occupation
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :profile
	devise 	:database_authenticatable, :registerable, :recoverable, :rememberable, 
			:trackable, :authentication_keys => [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  # GET /occupations
  # GET /occupations.json
  def index
    @occupations = Occupation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @occupations }
    end
  end

  # GET /occupations/1
  # GET /occupations/1.json
  def show
    @occupation = Occupation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @occupation }
    end
  end

  # GET /occupations/new
  # GET /occupations/new.json
  def new
    @occupation = Occupation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @occupation }
    end
  end

  # GET /occupations/1/edit
  def edit
    @occupation = Occupation.find(params[:id])
  end

  # POST /occupations
  # POST /occupations.json
  def create
    @occupation = Occupation.new(params[:occupation])

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to @occupation, notice: 'Occupation was successfully created.' }
        format.json { render json: @occupation, status: :created, location: @occupation }
      else
        format.html { render action: "new" }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /occupations/1
  # PUT /occupations/1.json
  def update
    @occupation = Occupation.find(params[:id])

    respond_to do |format|
      if @occupation.update_attributes(params[:occupation])
        format.html { redirect_to @occupation, notice: 'Occupation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1
  # DELETE /occupations/1.json
  def destroy
    @occupation = Occupation.find(params[:id])
    @occupation.destroy

    respond_to do |format|
      format.html { redirect_to occupations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json

  before_filter :authenticate_user!, :except => [:index]
   # :only => 

  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	# def create
	#   auth = request.env["omniauth.auth"]
	#   user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	#   session[:user_id] = user.id
	#   redirect_to root_url, :notice => "Signed in!"
	# end

	# def destroy
	#   session[:user_id] = nil
	#   redirect_to root_url, :notice => "Signed out!"
	# end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<!-- <div id="footer">
	<div class="content">
		<div class="links">
			<ul>
				<li><%= link_to "About", about_path %></li> |
				<li><%= link_to "FAQ", faq_path %></li> |
				<li><%= link_to "Terms", terms_path %></li> |
				<li><%= link_to "Tweets", tweets_path %></li>
			</ul>
		</div>
		<div class="social">
			<a href="http://www.twitter.com" target="_blank">
				<div class="twitter"><img src="/assets/twitter.png"></div>
			</a>
			<a href="http://www.facebook.com" target="_blank">
				<div class="facebook"><img src="/assets/facebook.png"></div>
			</a>
			<a href="http://www.googleplus.com" target="_blank">
				<div class="google-plus"><img src="/assets/gplus.png"></div>
			</a>
			<a href="http://www.linkedin.com" target="_blank">
				<div class="linked-in"><img src="/assets/linkedin.png"></div>
			</a>
		</div>
		<div class="copyright">
			Copyright 2013 We Are Utah Tech
		</div>
	</div>
</div> -->

app/views/layouts/_header.html.erb
<!-- <div class="header">
  <div class="content">
    <div class="sign-in sign-in-box">
      <div class="sign-in triangle"></div>
      <div class="sign-in google-login">Login with Google</div>
      <div class="sign-in facebook-login">Login with Facebook</div>
    </div>
    <div class="logo">
      <%= link_to "We Are Utah Tech", '/', id: "logo" %>
    </div>
    <div class="links">
      <ul>
        <li><%= link_to "Home", '/' %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Join", contact_path %></li>
        <li><div class="sign-in sign-in-link">Sign in</div></li>
      </ul>
    </div>
  </div>
</div> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>We Are Utah Tech</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,400,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Magra' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>